# Cofigurations
spring:
  datasource:
    url: jdbc:mysql://root:rDYSWZIFEnyiHQUqagsVFkzbkJZUuouB@junction.proxy.rlwy.net:12773/railway
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
# Server configurations
server:
  error:
    include-stacktrace: never

# JWT
api:
  security:
    secret: TZAG6XvmNpGjyPqPZro+Dsq2XORanQ+AwBTSvyKxUQU=

cors:
  allowed:
    origins: http://127.0.0.1:5500